package com.xz.web.entity;

import com.xz.framework.common.base.BasicBean;

public class Admin extends BasicBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.status
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.sex
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.contact
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.title
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Admin(Long id, String username, String password, Integer status, Boolean sex, String contact, String title, String createTimestamp, String updateTimestamp) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.status = status;
        this.sex = sex;
        this.contact = contact;
        this.title = title;
        this.createTimestamp = createTimestamp;
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Admin() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.status
     *
     * @return the value of admin.status
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.status
     *
     * @param status the value for admin.status
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.sex
     *
     * @return the value of admin.sex
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.sex
     *
     * @param sex the value for admin.sex
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.contact
     *
     * @return the value of admin.contact
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.contact
     *
     * @param contact the value for admin.contact
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.title
     *
     * @return the value of admin.title
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.title
     *
     * @param title the value for admin.title
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_timestamp
     *
     * @return the value of admin.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_timestamp
     *
     * @param createTimestamp the value for admin.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setCreateTimestamp(String createTimestamp) {
        this.createTimestamp = createTimestamp == null ? null : createTimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.update_timestamp
     *
     * @return the value of admin.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.update_timestamp
     *
     * @param updateTimestamp the value for admin.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setUpdateTimestamp(String updateTimestamp) {
        this.updateTimestamp = updateTimestamp == null ? null : updateTimestamp.trim();
    }
}