package com.xz.web.entity;

import com.xz.framework.common.base.BasicBean;

public class Resource extends BasicBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resource_name
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resource_code
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    private String resourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.status
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.create_timestamp
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    private String createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.update_timestamp
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    private String updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public Resource(Long id, String resourceName, String resourceCode, Integer status, String createTimestamp, String updateTimestamp) {
        this.id = id;
        this.resourceName = resourceName;
        this.resourceCode = resourceCode;
        this.status = status;
        this.createTimestamp = createTimestamp;
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public Resource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resource_name
     *
     * @return the value of resource.resource_name
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resource_name
     *
     * @param resourceName the value for resource.resource_name
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resource_code
     *
     * @return the value of resource.resource_code
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public String getResourceCode() {
        return resourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resource_code
     *
     * @param resourceCode the value for resource.resource_code
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public void setResourceCode(String resourceCode) {
        this.resourceCode = resourceCode == null ? null : resourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.status
     *
     * @return the value of resource.status
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.status
     *
     * @param status the value for resource.status
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.create_timestamp
     *
     * @return the value of resource.create_timestamp
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public String getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.create_timestamp
     *
     * @param createTimestamp the value for resource.create_timestamp
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public void setCreateTimestamp(String createTimestamp) {
        this.createTimestamp = createTimestamp == null ? null : createTimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.update_timestamp
     *
     * @return the value of resource.update_timestamp
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public String getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.update_timestamp
     *
     * @param updateTimestamp the value for resource.update_timestamp
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    public void setUpdateTimestamp(String updateTimestamp) {
        this.updateTimestamp = updateTimestamp == null ? null : updateTimestamp.trim();
    }
}