package com.xz.web.entity;

import com.xz.framework.common.base.BasicBean;

public class TcQianYanUrl extends BasicBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_qian_yan_url.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_qian_yan_url.yan_url
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String yanUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_qian_yan_url.qian_url
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String qianUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_qian_yan_url.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_qian_yan_url.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public TcQianYanUrl(Long id, String yanUrl, String qianUrl, String createTimestamp, String updateTimestamp) {
        this.id = id;
        this.yanUrl = yanUrl;
        this.qianUrl = qianUrl;
        this.createTimestamp = createTimestamp;
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public TcQianYanUrl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_qian_yan_url.id
     *
     * @return the value of tc_qian_yan_url.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_qian_yan_url.id
     *
     * @param id the value for tc_qian_yan_url.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_qian_yan_url.yan_url
     *
     * @return the value of tc_qian_yan_url.yan_url
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getYanUrl() {
        return yanUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_qian_yan_url.yan_url
     *
     * @param yanUrl the value for tc_qian_yan_url.yan_url
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setYanUrl(String yanUrl) {
        this.yanUrl = yanUrl == null ? null : yanUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_qian_yan_url.qian_url
     *
     * @return the value of tc_qian_yan_url.qian_url
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getQianUrl() {
        return qianUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_qian_yan_url.qian_url
     *
     * @param qianUrl the value for tc_qian_yan_url.qian_url
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setQianUrl(String qianUrl) {
        this.qianUrl = qianUrl == null ? null : qianUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_qian_yan_url.create_timestamp
     *
     * @return the value of tc_qian_yan_url.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_qian_yan_url.create_timestamp
     *
     * @param createTimestamp the value for tc_qian_yan_url.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setCreateTimestamp(String createTimestamp) {
        this.createTimestamp = createTimestamp == null ? null : createTimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_qian_yan_url.update_timestamp
     *
     * @return the value of tc_qian_yan_url.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_qian_yan_url.update_timestamp
     *
     * @param updateTimestamp the value for tc_qian_yan_url.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setUpdateTimestamp(String updateTimestamp) {
        this.updateTimestamp = updateTimestamp == null ? null : updateTimestamp.trim();
    }
}