package com.xz.web.entity;

import com.xz.framework.common.base.BasicBean;

public class TiLucky extends BasicBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.id
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.constellation_id
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Long constellationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_type1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_type2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_type3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyType3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_type4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyType4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_score1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Integer luckyScore1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_score2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Integer luckyScore2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_score3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Integer luckyScore3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_score4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Integer luckyScore4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.remind_today
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String remindToday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_type_more1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyTypeMore1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_type_more2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyTypeMore2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_type_more3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyTypeMore3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_type_more4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyTypeMore4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_score_more1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Integer luckyScoreMore1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_score_more2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Integer luckyScoreMore2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_score_more3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Integer luckyScoreMore3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_score_more4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Integer luckyScoreMore4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_words1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyWords1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_words2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyWords2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_words3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyWords3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_words4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyWords4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.to_do
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String toDo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.not_do
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String notDo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.publish_time
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.status
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.lucky_date
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String luckyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.create_timestamp
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_lucky.update_timestamp
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    private String updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public TiLucky(Long id, Long constellationId, String luckyType1, String luckyType2, String luckyType3, String luckyType4, Integer luckyScore1, Integer luckyScore2, Integer luckyScore3, Integer luckyScore4, String remindToday, String luckyTypeMore1, String luckyTypeMore2, String luckyTypeMore3, String luckyTypeMore4, Integer luckyScoreMore1, Integer luckyScoreMore2, Integer luckyScoreMore3, Integer luckyScoreMore4, String luckyWords1, String luckyWords2, String luckyWords3, String luckyWords4, String toDo, String notDo, String publishTime, Integer status, String luckyDate, String createTimestamp, String updateTimestamp) {
        this.id = id;
        this.constellationId = constellationId;
        this.luckyType1 = luckyType1;
        this.luckyType2 = luckyType2;
        this.luckyType3 = luckyType3;
        this.luckyType4 = luckyType4;
        this.luckyScore1 = luckyScore1;
        this.luckyScore2 = luckyScore2;
        this.luckyScore3 = luckyScore3;
        this.luckyScore4 = luckyScore4;
        this.remindToday = remindToday;
        this.luckyTypeMore1 = luckyTypeMore1;
        this.luckyTypeMore2 = luckyTypeMore2;
        this.luckyTypeMore3 = luckyTypeMore3;
        this.luckyTypeMore4 = luckyTypeMore4;
        this.luckyScoreMore1 = luckyScoreMore1;
        this.luckyScoreMore2 = luckyScoreMore2;
        this.luckyScoreMore3 = luckyScoreMore3;
        this.luckyScoreMore4 = luckyScoreMore4;
        this.luckyWords1 = luckyWords1;
        this.luckyWords2 = luckyWords2;
        this.luckyWords3 = luckyWords3;
        this.luckyWords4 = luckyWords4;
        this.toDo = toDo;
        this.notDo = notDo;
        this.publishTime = publishTime;
        this.status = status;
        this.luckyDate = luckyDate;
        this.createTimestamp = createTimestamp;
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public TiLucky() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.id
     *
     * @return the value of ti_lucky.id
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.id
     *
     * @param id the value for ti_lucky.id
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.constellation_id
     *
     * @return the value of ti_lucky.constellation_id
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Long getConstellationId() {
        return constellationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.constellation_id
     *
     * @param constellationId the value for ti_lucky.constellation_id
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setConstellationId(Long constellationId) {
        this.constellationId = constellationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_type1
     *
     * @return the value of ti_lucky.lucky_type1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyType1() {
        return luckyType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_type1
     *
     * @param luckyType1 the value for ti_lucky.lucky_type1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyType1(String luckyType1) {
        this.luckyType1 = luckyType1 == null ? null : luckyType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_type2
     *
     * @return the value of ti_lucky.lucky_type2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyType2() {
        return luckyType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_type2
     *
     * @param luckyType2 the value for ti_lucky.lucky_type2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyType2(String luckyType2) {
        this.luckyType2 = luckyType2 == null ? null : luckyType2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_type3
     *
     * @return the value of ti_lucky.lucky_type3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyType3() {
        return luckyType3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_type3
     *
     * @param luckyType3 the value for ti_lucky.lucky_type3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyType3(String luckyType3) {
        this.luckyType3 = luckyType3 == null ? null : luckyType3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_type4
     *
     * @return the value of ti_lucky.lucky_type4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyType4() {
        return luckyType4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_type4
     *
     * @param luckyType4 the value for ti_lucky.lucky_type4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyType4(String luckyType4) {
        this.luckyType4 = luckyType4 == null ? null : luckyType4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_score1
     *
     * @return the value of ti_lucky.lucky_score1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Integer getLuckyScore1() {
        return luckyScore1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_score1
     *
     * @param luckyScore1 the value for ti_lucky.lucky_score1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyScore1(Integer luckyScore1) {
        this.luckyScore1 = luckyScore1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_score2
     *
     * @return the value of ti_lucky.lucky_score2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Integer getLuckyScore2() {
        return luckyScore2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_score2
     *
     * @param luckyScore2 the value for ti_lucky.lucky_score2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyScore2(Integer luckyScore2) {
        this.luckyScore2 = luckyScore2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_score3
     *
     * @return the value of ti_lucky.lucky_score3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Integer getLuckyScore3() {
        return luckyScore3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_score3
     *
     * @param luckyScore3 the value for ti_lucky.lucky_score3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyScore3(Integer luckyScore3) {
        this.luckyScore3 = luckyScore3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_score4
     *
     * @return the value of ti_lucky.lucky_score4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Integer getLuckyScore4() {
        return luckyScore4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_score4
     *
     * @param luckyScore4 the value for ti_lucky.lucky_score4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyScore4(Integer luckyScore4) {
        this.luckyScore4 = luckyScore4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.remind_today
     *
     * @return the value of ti_lucky.remind_today
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getRemindToday() {
        return remindToday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.remind_today
     *
     * @param remindToday the value for ti_lucky.remind_today
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setRemindToday(String remindToday) {
        this.remindToday = remindToday == null ? null : remindToday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_type_more1
     *
     * @return the value of ti_lucky.lucky_type_more1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyTypeMore1() {
        return luckyTypeMore1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_type_more1
     *
     * @param luckyTypeMore1 the value for ti_lucky.lucky_type_more1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyTypeMore1(String luckyTypeMore1) {
        this.luckyTypeMore1 = luckyTypeMore1 == null ? null : luckyTypeMore1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_type_more2
     *
     * @return the value of ti_lucky.lucky_type_more2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyTypeMore2() {
        return luckyTypeMore2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_type_more2
     *
     * @param luckyTypeMore2 the value for ti_lucky.lucky_type_more2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyTypeMore2(String luckyTypeMore2) {
        this.luckyTypeMore2 = luckyTypeMore2 == null ? null : luckyTypeMore2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_type_more3
     *
     * @return the value of ti_lucky.lucky_type_more3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyTypeMore3() {
        return luckyTypeMore3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_type_more3
     *
     * @param luckyTypeMore3 the value for ti_lucky.lucky_type_more3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyTypeMore3(String luckyTypeMore3) {
        this.luckyTypeMore3 = luckyTypeMore3 == null ? null : luckyTypeMore3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_type_more4
     *
     * @return the value of ti_lucky.lucky_type_more4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyTypeMore4() {
        return luckyTypeMore4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_type_more4
     *
     * @param luckyTypeMore4 the value for ti_lucky.lucky_type_more4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyTypeMore4(String luckyTypeMore4) {
        this.luckyTypeMore4 = luckyTypeMore4 == null ? null : luckyTypeMore4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_score_more1
     *
     * @return the value of ti_lucky.lucky_score_more1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Integer getLuckyScoreMore1() {
        return luckyScoreMore1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_score_more1
     *
     * @param luckyScoreMore1 the value for ti_lucky.lucky_score_more1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyScoreMore1(Integer luckyScoreMore1) {
        this.luckyScoreMore1 = luckyScoreMore1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_score_more2
     *
     * @return the value of ti_lucky.lucky_score_more2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Integer getLuckyScoreMore2() {
        return luckyScoreMore2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_score_more2
     *
     * @param luckyScoreMore2 the value for ti_lucky.lucky_score_more2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyScoreMore2(Integer luckyScoreMore2) {
        this.luckyScoreMore2 = luckyScoreMore2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_score_more3
     *
     * @return the value of ti_lucky.lucky_score_more3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Integer getLuckyScoreMore3() {
        return luckyScoreMore3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_score_more3
     *
     * @param luckyScoreMore3 the value for ti_lucky.lucky_score_more3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyScoreMore3(Integer luckyScoreMore3) {
        this.luckyScoreMore3 = luckyScoreMore3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_score_more4
     *
     * @return the value of ti_lucky.lucky_score_more4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Integer getLuckyScoreMore4() {
        return luckyScoreMore4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_score_more4
     *
     * @param luckyScoreMore4 the value for ti_lucky.lucky_score_more4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyScoreMore4(Integer luckyScoreMore4) {
        this.luckyScoreMore4 = luckyScoreMore4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_words1
     *
     * @return the value of ti_lucky.lucky_words1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyWords1() {
        return luckyWords1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_words1
     *
     * @param luckyWords1 the value for ti_lucky.lucky_words1
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyWords1(String luckyWords1) {
        this.luckyWords1 = luckyWords1 == null ? null : luckyWords1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_words2
     *
     * @return the value of ti_lucky.lucky_words2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyWords2() {
        return luckyWords2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_words2
     *
     * @param luckyWords2 the value for ti_lucky.lucky_words2
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyWords2(String luckyWords2) {
        this.luckyWords2 = luckyWords2 == null ? null : luckyWords2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_words3
     *
     * @return the value of ti_lucky.lucky_words3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyWords3() {
        return luckyWords3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_words3
     *
     * @param luckyWords3 the value for ti_lucky.lucky_words3
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyWords3(String luckyWords3) {
        this.luckyWords3 = luckyWords3 == null ? null : luckyWords3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_words4
     *
     * @return the value of ti_lucky.lucky_words4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyWords4() {
        return luckyWords4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_words4
     *
     * @param luckyWords4 the value for ti_lucky.lucky_words4
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyWords4(String luckyWords4) {
        this.luckyWords4 = luckyWords4 == null ? null : luckyWords4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.to_do
     *
     * @return the value of ti_lucky.to_do
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getToDo() {
        return toDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.to_do
     *
     * @param toDo the value for ti_lucky.to_do
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setToDo(String toDo) {
        this.toDo = toDo == null ? null : toDo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.not_do
     *
     * @return the value of ti_lucky.not_do
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getNotDo() {
        return notDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.not_do
     *
     * @param notDo the value for ti_lucky.not_do
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setNotDo(String notDo) {
        this.notDo = notDo == null ? null : notDo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.publish_time
     *
     * @return the value of ti_lucky.publish_time
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.publish_time
     *
     * @param publishTime the value for ti_lucky.publish_time
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime == null ? null : publishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.status
     *
     * @return the value of ti_lucky.status
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.status
     *
     * @param status the value for ti_lucky.status
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.lucky_date
     *
     * @return the value of ti_lucky.lucky_date
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getLuckyDate() {
        return luckyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.lucky_date
     *
     * @param luckyDate the value for ti_lucky.lucky_date
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setLuckyDate(String luckyDate) {
        this.luckyDate = luckyDate == null ? null : luckyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.create_timestamp
     *
     * @return the value of ti_lucky.create_timestamp
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.create_timestamp
     *
     * @param createTimestamp the value for ti_lucky.create_timestamp
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setCreateTimestamp(String createTimestamp) {
        this.createTimestamp = createTimestamp == null ? null : createTimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_lucky.update_timestamp
     *
     * @return the value of ti_lucky.update_timestamp
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public String getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_lucky.update_timestamp
     *
     * @param updateTimestamp the value for ti_lucky.update_timestamp
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    public void setUpdateTimestamp(String updateTimestamp) {
        this.updateTimestamp = updateTimestamp == null ? null : updateTimestamp.trim();
    }
}