package com.xz.web.entity;

import com.xz.framework.common.base.BasicBean;

public class TiUserQianList extends BasicBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.qian_date
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String qianDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.status
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.qian_name
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String qianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.qian_content
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String qianContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.user_id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.friend_open_id1
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String friendOpenId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.friend_open_id2
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String friendOpenId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.friend_open_id3
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String friendOpenId3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.friend_open_id4
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String friendOpenId4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.friend_open_id5
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String friendOpenId5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_user_qian_list.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public TiUserQianList(Long id, String qianDate, Integer status, String qianName, String qianContent, Long userId, String friendOpenId1, String friendOpenId2, String friendOpenId3, String friendOpenId4, String friendOpenId5, String createTimestamp, String updateTimestamp) {
        this.id = id;
        this.qianDate = qianDate;
        this.status = status;
        this.qianName = qianName;
        this.qianContent = qianContent;
        this.userId = userId;
        this.friendOpenId1 = friendOpenId1;
        this.friendOpenId2 = friendOpenId2;
        this.friendOpenId3 = friendOpenId3;
        this.friendOpenId4 = friendOpenId4;
        this.friendOpenId5 = friendOpenId5;
        this.createTimestamp = createTimestamp;
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public TiUserQianList() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.id
     *
     * @return the value of ti_user_qian_list.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.id
     *
     * @param id the value for ti_user_qian_list.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.qian_date
     *
     * @return the value of ti_user_qian_list.qian_date
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getQianDate() {
        return qianDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.qian_date
     *
     * @param qianDate the value for ti_user_qian_list.qian_date
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setQianDate(String qianDate) {
        this.qianDate = qianDate == null ? null : qianDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.status
     *
     * @return the value of ti_user_qian_list.status
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.status
     *
     * @param status the value for ti_user_qian_list.status
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.qian_name
     *
     * @return the value of ti_user_qian_list.qian_name
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getQianName() {
        return qianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.qian_name
     *
     * @param qianName the value for ti_user_qian_list.qian_name
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setQianName(String qianName) {
        this.qianName = qianName == null ? null : qianName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.qian_content
     *
     * @return the value of ti_user_qian_list.qian_content
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getQianContent() {
        return qianContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.qian_content
     *
     * @param qianContent the value for ti_user_qian_list.qian_content
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setQianContent(String qianContent) {
        this.qianContent = qianContent == null ? null : qianContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.user_id
     *
     * @return the value of ti_user_qian_list.user_id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.user_id
     *
     * @param userId the value for ti_user_qian_list.user_id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.friend_open_id1
     *
     * @return the value of ti_user_qian_list.friend_open_id1
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getFriendOpenId1() {
        return friendOpenId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.friend_open_id1
     *
     * @param friendOpenId1 the value for ti_user_qian_list.friend_open_id1
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setFriendOpenId1(String friendOpenId1) {
        this.friendOpenId1 = friendOpenId1 == null ? null : friendOpenId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.friend_open_id2
     *
     * @return the value of ti_user_qian_list.friend_open_id2
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getFriendOpenId2() {
        return friendOpenId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.friend_open_id2
     *
     * @param friendOpenId2 the value for ti_user_qian_list.friend_open_id2
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setFriendOpenId2(String friendOpenId2) {
        this.friendOpenId2 = friendOpenId2 == null ? null : friendOpenId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.friend_open_id3
     *
     * @return the value of ti_user_qian_list.friend_open_id3
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getFriendOpenId3() {
        return friendOpenId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.friend_open_id3
     *
     * @param friendOpenId3 the value for ti_user_qian_list.friend_open_id3
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setFriendOpenId3(String friendOpenId3) {
        this.friendOpenId3 = friendOpenId3 == null ? null : friendOpenId3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.friend_open_id4
     *
     * @return the value of ti_user_qian_list.friend_open_id4
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getFriendOpenId4() {
        return friendOpenId4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.friend_open_id4
     *
     * @param friendOpenId4 the value for ti_user_qian_list.friend_open_id4
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setFriendOpenId4(String friendOpenId4) {
        this.friendOpenId4 = friendOpenId4 == null ? null : friendOpenId4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.friend_open_id5
     *
     * @return the value of ti_user_qian_list.friend_open_id5
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getFriendOpenId5() {
        return friendOpenId5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.friend_open_id5
     *
     * @param friendOpenId5 the value for ti_user_qian_list.friend_open_id5
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setFriendOpenId5(String friendOpenId5) {
        this.friendOpenId5 = friendOpenId5 == null ? null : friendOpenId5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.create_timestamp
     *
     * @return the value of ti_user_qian_list.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.create_timestamp
     *
     * @param createTimestamp the value for ti_user_qian_list.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setCreateTimestamp(String createTimestamp) {
        this.createTimestamp = createTimestamp == null ? null : createTimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_user_qian_list.update_timestamp
     *
     * @return the value of ti_user_qian_list.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_user_qian_list.update_timestamp
     *
     * @param updateTimestamp the value for ti_user_qian_list.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setUpdateTimestamp(String updateTimestamp) {
        this.updateTimestamp = updateTimestamp == null ? null : updateTimestamp.trim();
    }
}