package com.xz.web.entity;

import com.xz.framework.common.base.BasicBean;

public class TiYanList extends BasicBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_yan_list.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_yan_list.constellation_id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private Long constellationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_yan_list.prev_pic
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String prevPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_yan_list.speech
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String speech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_yan_list.publish_person
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String publishPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_yan_list.publish_status
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_yan_list.publish_time
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_yan_list.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_yan_list.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    private String updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public TiYanList(Long id, Long constellationId, String prevPic, String speech, String publishPerson, String publishStatus, String publishTime, String createTimestamp, String updateTimestamp) {
        this.id = id;
        this.constellationId = constellationId;
        this.prevPic = prevPic;
        this.speech = speech;
        this.publishPerson = publishPerson;
        this.publishStatus = publishStatus;
        this.publishTime = publishTime;
        this.createTimestamp = createTimestamp;
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public TiYanList() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_yan_list.id
     *
     * @return the value of ti_yan_list.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_yan_list.id
     *
     * @param id the value for ti_yan_list.id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_yan_list.constellation_id
     *
     * @return the value of ti_yan_list.constellation_id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public Long getConstellationId() {
        return constellationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_yan_list.constellation_id
     *
     * @param constellationId the value for ti_yan_list.constellation_id
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setConstellationId(Long constellationId) {
        this.constellationId = constellationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_yan_list.prev_pic
     *
     * @return the value of ti_yan_list.prev_pic
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getPrevPic() {
        return prevPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_yan_list.prev_pic
     *
     * @param prevPic the value for ti_yan_list.prev_pic
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setPrevPic(String prevPic) {
        this.prevPic = prevPic == null ? null : prevPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_yan_list.speech
     *
     * @return the value of ti_yan_list.speech
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getSpeech() {
        return speech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_yan_list.speech
     *
     * @param speech the value for ti_yan_list.speech
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setSpeech(String speech) {
        this.speech = speech == null ? null : speech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_yan_list.publish_person
     *
     * @return the value of ti_yan_list.publish_person
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getPublishPerson() {
        return publishPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_yan_list.publish_person
     *
     * @param publishPerson the value for ti_yan_list.publish_person
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setPublishPerson(String publishPerson) {
        this.publishPerson = publishPerson == null ? null : publishPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_yan_list.publish_status
     *
     * @return the value of ti_yan_list.publish_status
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_yan_list.publish_status
     *
     * @param publishStatus the value for ti_yan_list.publish_status
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setPublishStatus(String publishStatus) {
        this.publishStatus = publishStatus == null ? null : publishStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_yan_list.publish_time
     *
     * @return the value of ti_yan_list.publish_time
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_yan_list.publish_time
     *
     * @param publishTime the value for ti_yan_list.publish_time
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime == null ? null : publishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_yan_list.create_timestamp
     *
     * @return the value of ti_yan_list.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_yan_list.create_timestamp
     *
     * @param createTimestamp the value for ti_yan_list.create_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setCreateTimestamp(String createTimestamp) {
        this.createTimestamp = createTimestamp == null ? null : createTimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_yan_list.update_timestamp
     *
     * @return the value of ti_yan_list.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public String getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_yan_list.update_timestamp
     *
     * @param updateTimestamp the value for ti_yan_list.update_timestamp
     *
     * @mbggenerated Sun May 13 16:14:16 CST 2018
     */
    public void setUpdateTimestamp(String updateTimestamp) {
        this.updateTimestamp = updateTimestamp == null ? null : updateTimestamp.trim();
    }
}