package com.xz.web.mapper;

import com.xz.web.entity.TcConstellation;
import com.xz.web.entity.TcConstellationExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TcConstellationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @SelectProvider(type=TcConstellationSqlProvider.class, method="countByExample")
    int countByExample(TcConstellationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @DeleteProvider(type=TcConstellationSqlProvider.class, method="deleteByExample")
    int deleteByExample(TcConstellationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Delete({
        "delete from tc_constellation",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Insert({
        "insert into tc_constellation (constellation_name, start_date, ",
        "end_date, picture_url, ",
        "remark, create_timestamp, ",
        "update_timestamp)",
        "values (#{constellationName,jdbcType=VARCHAR}, #{startDate,jdbcType=VARCHAR}, ",
        "#{endDate,jdbcType=VARCHAR}, #{pictureUrl,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{createTimestamp,jdbcType=VARCHAR}, ",
        "#{updateTimestamp,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(TcConstellation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @InsertProvider(type=TcConstellationSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(TcConstellation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @SelectProvider(type=TcConstellationSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="constellation_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="start_date", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="end_date", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="picture_url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remark", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<TcConstellation> selectByExample(TcConstellationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Select({
        "select",
        "id, constellation_name, start_date, end_date, picture_url, remark, create_timestamp, ",
        "update_timestamp",
        "from tc_constellation",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="constellation_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="start_date", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="end_date", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="picture_url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remark", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    TcConstellation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @UpdateProvider(type=TcConstellationSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TcConstellation record, @Param("example") TcConstellationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @UpdateProvider(type=TcConstellationSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TcConstellation record, @Param("example") TcConstellationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @UpdateProvider(type=TcConstellationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TcConstellation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_constellation
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Update({
        "update tc_constellation",
        "set constellation_name = #{constellationName,jdbcType=VARCHAR},",
          "start_date = #{startDate,jdbcType=VARCHAR},",
          "end_date = #{endDate,jdbcType=VARCHAR},",
          "picture_url = #{pictureUrl,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_timestamp = #{createTimestamp,jdbcType=VARCHAR},",
          "update_timestamp = #{updateTimestamp,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TcConstellation record);
}