package com.xz.web.mapper;

import com.xz.web.entity.TcQianYanUrl;
import com.xz.web.entity.TcQianYanUrlExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TcQianYanUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @SelectProvider(type=TcQianYanUrlSqlProvider.class, method="countByExample")
    int countByExample(TcQianYanUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @DeleteProvider(type=TcQianYanUrlSqlProvider.class, method="deleteByExample")
    int deleteByExample(TcQianYanUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @Delete({
        "delete from tc_qian_yan_url",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @Insert({
        "insert into tc_qian_yan_url (yan_url, qian_url, ",
        "create_timestamp, update_timestamp)",
        "values (#{yanUrl,jdbcType=VARCHAR}, #{qianUrl,jdbcType=VARCHAR}, ",
        "#{createTimestamp,jdbcType=VARCHAR}, #{updateTimestamp,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(TcQianYanUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @InsertProvider(type=TcQianYanUrlSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(TcQianYanUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @SelectProvider(type=TcQianYanUrlSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="yan_url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="qian_url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<TcQianYanUrl> selectByExample(TcQianYanUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @Select({
        "select",
        "id, yan_url, qian_url, create_timestamp, update_timestamp",
        "from tc_qian_yan_url",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="yan_url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="qian_url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    TcQianYanUrl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @UpdateProvider(type=TcQianYanUrlSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TcQianYanUrl record, @Param("example") TcQianYanUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @UpdateProvider(type=TcQianYanUrlSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TcQianYanUrl record, @Param("example") TcQianYanUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @UpdateProvider(type=TcQianYanUrlSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TcQianYanUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_qian_yan_url
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @Update({
        "update tc_qian_yan_url",
        "set yan_url = #{yanUrl,jdbcType=VARCHAR},",
          "qian_url = #{qianUrl,jdbcType=VARCHAR},",
          "create_timestamp = #{createTimestamp,jdbcType=VARCHAR},",
          "update_timestamp = #{updateTimestamp,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TcQianYanUrl record);
}