package com.xz.web.mapper;

import com.xz.web.entity.TiLucky;
import com.xz.web.entity.TiLuckyExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TiLuckyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @SelectProvider(type=TiLuckySqlProvider.class, method="countByExample")
    int countByExample(TiLuckyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @DeleteProvider(type=TiLuckySqlProvider.class, method="deleteByExample")
    int deleteByExample(TiLuckyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Delete({
        "delete from ti_lucky",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Insert({
        "insert into ti_lucky (constellation_id, lucky_type1, ",
        "lucky_type2, lucky_type3, ",
        "lucky_type4, lucky_score1, ",
        "lucky_score2, lucky_score3, ",
        "lucky_score4, remind_today, ",
        "lucky_type_more1, lucky_type_more2, ",
        "lucky_type_more3, lucky_type_more4, ",
        "lucky_score_more1, lucky_score_more2, ",
        "lucky_score_more3, lucky_score_more4, ",
        "lucky_words1, lucky_words2, ",
        "lucky_words3, lucky_words4, ",
        "to_do, not_do, publish_time, ",
        "lucky_date, create_timestamp, ",
        "update_timestamp)",
        "values (#{constellationId,jdbcType=BIGINT}, #{luckyType1,jdbcType=VARCHAR}, ",
        "#{luckyType2,jdbcType=VARCHAR}, #{luckyType3,jdbcType=VARCHAR}, ",
        "#{luckyType4,jdbcType=VARCHAR}, #{luckyScore1,jdbcType=INTEGER}, ",
        "#{luckyScore2,jdbcType=INTEGER}, #{luckyScore3,jdbcType=INTEGER}, ",
        "#{luckyScore4,jdbcType=INTEGER}, #{remindToday,jdbcType=VARCHAR}, ",
        "#{luckyTypeMore1,jdbcType=VARCHAR}, #{luckyTypeMore2,jdbcType=VARCHAR}, ",
        "#{luckyTypeMore3,jdbcType=VARCHAR}, #{luckyTypeMore4,jdbcType=VARCHAR}, ",
        "#{luckyScoreMore1,jdbcType=INTEGER}, #{luckyScoreMore2,jdbcType=INTEGER}, ",
        "#{luckyScoreMore3,jdbcType=INTEGER}, #{luckyScoreMore4,jdbcType=INTEGER}, ",
        "#{luckyWords1,jdbcType=VARCHAR}, #{luckyWords2,jdbcType=VARCHAR}, ",
        "#{luckyWords3,jdbcType=VARCHAR}, #{luckyWords4,jdbcType=VARCHAR}, ",
        "#{toDo,jdbcType=VARCHAR}, #{notDo,jdbcType=VARCHAR}, #{publishTime,jdbcType=VARCHAR}, ",
        "#{luckyDate,jdbcType=VARCHAR}, #{createTimestamp,jdbcType=VARCHAR}, ",
        "#{updateTimestamp,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(TiLucky record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @InsertProvider(type=TiLuckySqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(TiLucky record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @SelectProvider(type=TiLuckySqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="constellation_id", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="lucky_type1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type3", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type4", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_score1", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score2", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score3", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score4", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="remind_today", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type_more1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type_more2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type_more3", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type_more4", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_score_more1", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score_more2", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score_more3", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score_more4", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_words1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_words2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_words3", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_words4", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="to_do", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="not_do", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="publish_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_date", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<TiLucky> selectByExample(TiLuckyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Select({
        "select",
        "id, constellation_id, lucky_type1, lucky_type2, lucky_type3, lucky_type4, lucky_score1, ",
        "lucky_score2, lucky_score3, lucky_score4, remind_today, lucky_type_more1, lucky_type_more2, ",
        "lucky_type_more3, lucky_type_more4, lucky_score_more1, lucky_score_more2, lucky_score_more3, ",
        "lucky_score_more4, lucky_words1, lucky_words2, lucky_words3, lucky_words4, to_do, ",
        "not_do, publish_time, lucky_date, create_timestamp, update_timestamp",
        "from ti_lucky",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="constellation_id", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="lucky_type1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type3", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type4", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_score1", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score2", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score3", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score4", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="remind_today", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type_more1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type_more2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type_more3", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_type_more4", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_score_more1", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score_more2", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score_more3", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_score_more4", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lucky_words1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_words2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_words3", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_words4", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="to_do", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="not_do", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="publish_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="lucky_date", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    TiLucky selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @UpdateProvider(type=TiLuckySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TiLucky record, @Param("example") TiLuckyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @UpdateProvider(type=TiLuckySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TiLucky record, @Param("example") TiLuckyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @UpdateProvider(type=TiLuckySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TiLucky record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_lucky
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Update({
        "update ti_lucky",
        "set constellation_id = #{constellationId,jdbcType=BIGINT},",
          "lucky_type1 = #{luckyType1,jdbcType=VARCHAR},",
          "lucky_type2 = #{luckyType2,jdbcType=VARCHAR},",
          "lucky_type3 = #{luckyType3,jdbcType=VARCHAR},",
          "lucky_type4 = #{luckyType4,jdbcType=VARCHAR},",
          "lucky_score1 = #{luckyScore1,jdbcType=INTEGER},",
          "lucky_score2 = #{luckyScore2,jdbcType=INTEGER},",
          "lucky_score3 = #{luckyScore3,jdbcType=INTEGER},",
          "lucky_score4 = #{luckyScore4,jdbcType=INTEGER},",
          "remind_today = #{remindToday,jdbcType=VARCHAR},",
          "lucky_type_more1 = #{luckyTypeMore1,jdbcType=VARCHAR},",
          "lucky_type_more2 = #{luckyTypeMore2,jdbcType=VARCHAR},",
          "lucky_type_more3 = #{luckyTypeMore3,jdbcType=VARCHAR},",
          "lucky_type_more4 = #{luckyTypeMore4,jdbcType=VARCHAR},",
          "lucky_score_more1 = #{luckyScoreMore1,jdbcType=INTEGER},",
          "lucky_score_more2 = #{luckyScoreMore2,jdbcType=INTEGER},",
          "lucky_score_more3 = #{luckyScoreMore3,jdbcType=INTEGER},",
          "lucky_score_more4 = #{luckyScoreMore4,jdbcType=INTEGER},",
          "lucky_words1 = #{luckyWords1,jdbcType=VARCHAR},",
          "lucky_words2 = #{luckyWords2,jdbcType=VARCHAR},",
          "lucky_words3 = #{luckyWords3,jdbcType=VARCHAR},",
          "lucky_words4 = #{luckyWords4,jdbcType=VARCHAR},",
          "to_do = #{toDo,jdbcType=VARCHAR},",
          "not_do = #{notDo,jdbcType=VARCHAR},",
          "publish_time = #{publishTime,jdbcType=VARCHAR},",
          "lucky_date = #{luckyDate,jdbcType=VARCHAR},",
          "create_timestamp = #{createTimestamp,jdbcType=VARCHAR},",
          "update_timestamp = #{updateTimestamp,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TiLucky record);
}