package com.xz.web.mapper;

import com.xz.web.entity.TiUserQianList;
import com.xz.web.entity.TiUserQianListExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TiUserQianListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @SelectProvider(type=TiUserQianListSqlProvider.class, method="countByExample")
    int countByExample(TiUserQianListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @DeleteProvider(type=TiUserQianListSqlProvider.class, method="deleteByExample")
    int deleteByExample(TiUserQianListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @Delete({
        "delete from ti_user_qian_list",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @Insert({
        "insert into ti_user_qian_list (qian_date, status, ",
        "qian_name, qian_content, ",
        "user_id, friend_open_id1, ",
        "friend_open_id2, friend_open_id3, ",
        "friend_open_id4, friend_open_id5, ",
        "create_timestamp, update_timestamp)",
        "values (#{qianDate,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{qianName,jdbcType=VARCHAR}, #{qianContent,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=BIGINT}, #{friendOpenId1,jdbcType=VARCHAR}, ",
        "#{friendOpenId2,jdbcType=VARCHAR}, #{friendOpenId3,jdbcType=VARCHAR}, ",
        "#{friendOpenId4,jdbcType=VARCHAR}, #{friendOpenId5,jdbcType=VARCHAR}, ",
        "#{createTimestamp,jdbcType=VARCHAR}, #{updateTimestamp,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(TiUserQianList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @InsertProvider(type=TiUserQianListSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(TiUserQianList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @SelectProvider(type=TiUserQianListSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="qian_date", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="qian_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="qian_content", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="user_id", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="friend_open_id1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="friend_open_id2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="friend_open_id3", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="friend_open_id4", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="friend_open_id5", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<TiUserQianList> selectByExample(TiUserQianListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @Select({
        "select",
        "id, qian_date, status, qian_name, qian_content, user_id, friend_open_id1, friend_open_id2, ",
        "friend_open_id3, friend_open_id4, friend_open_id5, create_timestamp, update_timestamp",
        "from ti_user_qian_list",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="qian_date", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="qian_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="qian_content", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="user_id", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="friend_open_id1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="friend_open_id2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="friend_open_id3", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="friend_open_id4", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="friend_open_id5", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    TiUserQianList selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @UpdateProvider(type=TiUserQianListSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TiUserQianList record, @Param("example") TiUserQianListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @UpdateProvider(type=TiUserQianListSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TiUserQianList record, @Param("example") TiUserQianListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @UpdateProvider(type=TiUserQianListSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TiUserQianList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_user_qian_list
     *
     * @mbggenerated Sat May 12 22:20:50 CST 2018
     */
    @Update({
        "update ti_user_qian_list",
        "set qian_date = #{qianDate,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "qian_name = #{qianName,jdbcType=VARCHAR},",
          "qian_content = #{qianContent,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "friend_open_id1 = #{friendOpenId1,jdbcType=VARCHAR},",
          "friend_open_id2 = #{friendOpenId2,jdbcType=VARCHAR},",
          "friend_open_id3 = #{friendOpenId3,jdbcType=VARCHAR},",
          "friend_open_id4 = #{friendOpenId4,jdbcType=VARCHAR},",
          "friend_open_id5 = #{friendOpenId5,jdbcType=VARCHAR},",
          "create_timestamp = #{createTimestamp,jdbcType=VARCHAR},",
          "update_timestamp = #{updateTimestamp,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TiUserQianList record);
}