package com.xz.web.mapper;

import com.xz.web.entity.TiYanList;
import com.xz.web.entity.TiYanListExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TiYanListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @SelectProvider(type=TiYanListSqlProvider.class, method="countByExample")
    int countByExample(TiYanListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @DeleteProvider(type=TiYanListSqlProvider.class, method="deleteByExample")
    int deleteByExample(TiYanListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Delete({
        "delete from ti_yan_list",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Insert({
        "insert into ti_yan_list (constellation_id, prev_pic, ",
        "publish_person, publish_status, ",
        "publish_time, create_timestamp, ",
        "update_timestamp)",
        "values (#{constellationId,jdbcType=BIGINT}, #{prevPic,jdbcType=VARCHAR}, ",
        "#{publishPerson,jdbcType=VARCHAR}, #{publishStatus,jdbcType=VARCHAR}, ",
        "#{publishTime,jdbcType=VARCHAR}, #{createTimestamp,jdbcType=VARCHAR}, ",
        "#{updateTimestamp,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(TiYanList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @InsertProvider(type=TiYanListSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(TiYanList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @SelectProvider(type=TiYanListSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="constellation_id", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="prev_pic", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="publish_person", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="publish_status", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="publish_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<TiYanList> selectByExample(TiYanListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Select({
        "select",
        "id, constellation_id, prev_pic, publish_person, publish_status, publish_time, ",
        "create_timestamp, update_timestamp",
        "from ti_yan_list",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="constellation_id", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="prev_pic", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="publish_person", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="publish_status", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="publish_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_timestamp", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    TiYanList selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @UpdateProvider(type=TiYanListSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TiYanList record, @Param("example") TiYanListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @UpdateProvider(type=TiYanListSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TiYanList record, @Param("example") TiYanListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @UpdateProvider(type=TiYanListSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TiYanList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_yan_list
     *
     * @mbggenerated Sat May 12 18:17:19 CST 2018
     */
    @Update({
        "update ti_yan_list",
        "set constellation_id = #{constellationId,jdbcType=BIGINT},",
          "prev_pic = #{prevPic,jdbcType=VARCHAR},",
          "publish_person = #{publishPerson,jdbcType=VARCHAR},",
          "publish_status = #{publishStatus,jdbcType=VARCHAR},",
          "publish_time = #{publishTime,jdbcType=VARCHAR},",
          "create_timestamp = #{createTimestamp,jdbcType=VARCHAR},",
          "update_timestamp = #{updateTimestamp,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TiYanList record);
}